acendTraining:
  servicePort: 8080
  deployments:
    - 
      name: acend
      replicaCount: 2
      image:
        repository: quay.io/acend/kubernetes-basics-training
        pullPolicy: Always
        tag: ""
        tagsuffix: ""
      ingress:
        secretOverride: acend-wildcard
        appname: kubernetes-basics
        domain: training.acend.ch
    - 
      name: mobi
      replicaCount: 2
      image:
        repository: quay.io/acend/kubernetes-basics-training
        pullPolicy: Always
        tag: ""
        tagsuffix: "-mobi"
      ingress:
        secretOverride: acend-wildcard
        appname: kubernetes-basics-mobi
        domain: training.puzzle.ch
    -
      name: openshift
      replicaCount: 2
      image:
        repository: quay.io/acend/kubernetes-basics-training
        pullPolicy: Always
        tag: ""
        tagsuffix: "-openshift"
      ingress:
        secretOverride: acend-wildcard
        appname: openshift-basics
        domain: training.acend.ch
    -
      name: baloise
      replicaCount: 2
      image:
        repository: quay.io/acend/kubernetes-basics-training
        pullPolicy: Always
        tag: ""
        tagsuffix: "-baloise"
      ingress:
        secretOverride: acend-wildcard
        appname: openshift-basics-baloise
        domain: training.acend.ch
    -
      name: sbb
      replicaCount: 2
      image:
        repository: quay.io/acend/kubernetes-basics-training
        pullPolicy: Always
        tag: ""
        tagsuffix: "-sbb"
      ingress:
        secretOverride: acend-wildcard
        appname: openshift-basics-sbb
        domain: training.acend.ch
    -
      name: bfh
      replicaCount: 2
      image:
        repository: quay.io/acend/kubernetes-basics-training
        pullPolicy: Always
        tag: ""
        tagsuffix: "-bfh"
      ingress:
        annotations:
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        secretOverride: cert-timkoko
        appname: openshift-basics-bfh
        domain: training.tim-koko.ch
    -
      name: techlab
      replicaCount: 2
      image:
        repository: quay.io/appuio/techlab
        pullPolicy: Always
        tag: ""
        tagsuffix: ""
      ingress:
        annotations:
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        appname: techlab
        domain: training.acend.ch
        domainmain: appuio.ch

nameOverride: "acend-kubernetes-basics"
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
