acendTraining:
  servicePort: 8080
  deployments:
    - 
      name: acend
      replicaCount: 1
      image:
        repository: quay.io/acend/kubernetes-basics-training
        pullPolicy: Always
        tag: ""
        tagsuffix: ""
      ingress:
        annotations: 
          kubernetes.io/ingress.class: nginx-public
        secretOverride: acend-wildcard
        appname: kubernetes-basics
        domain: training.acend.ch
    - 
      name: mobi
      replicaCount: 1
      image:
        repository: quay.io/acend/kubernetes-basics-training
        pullPolicy: Always
        tag: ""
        tagsuffix: "-mobi"
      ingress:
        annotations: 
          kubernetes.io/ingress.class: nginx-public
        useDefaultSecret: true
        appname: kubernetes-basics-mobi
        domain: k8s.puzzle.ch
    - 
      name: rancher
      replicaCount: 1
      image:
        repository: quay.io/acend/kubernetes-basics-training
        pullPolicy: Always
        tag: ""
        tagsuffix: "-rancher"
      ingress:
        annotations: 
          kubernetes.io/ingress.class: nginx-public
        secretOverride: acend-wildcard
        appname: kubernetes-basics-rancher
        domain: training.acend.ch
    - 
      name: openshift
      replicaCount: 1
      image:
        repository: quay.io/acend/kubernetes-basics-training
        pullPolicy: Always
        tag: ""
        tagsuffix: "-openshift"
      ingress:
        annotations: 
          kubernetes.io/ingress.class: nginx-public
        secretOverride: acend-wildcard
        appname: openshift-basics
        domain: training.acend.ch
    - 
      name: netcetera
      replicaCount: 1
      image:
        repository: quay.io/acend/kubernetes-basics-training
        pullPolicy: Always
        tag: ""
        tagsuffix: "-netcetera"
      ingress:
        annotations: 
          kubernetes.io/ingress.class: nginx-public
        secretOverride: acend-wildcard
        appname: kubernetes-basics-netcetera
        domain: training.acend.ch



nameOverride: "acend-kubernetes-basics"
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
