apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-web-go
  annotations:
    kubernetes.io/ingress.class: "nginx-external"

spec:
  rules:
    - host: example-web-go-<namespace>.training.test.netcetera.com
      http:
        paths:
          - path: /
            backend:
              serviceName: example-web-go
              servicePort: 5000
