[params]
enabledModule = "base rancher customer netcetera"

customer = "netcetera"

[params.images]
acendAwesomeApp-example-web-go = "docker-registry-mirror.netcetera.com/acend/example-web-go:latest"
acendAwesomeApp-example-web-python = "docker-registry-mirror.netcetera.com/acend/example-web-python:latest"
nginxinc-nginx-unprivileged = "docker-registry-mirror.netcetera.com/nginxinc/nginx-unprivileged:latest"
nginxinc-nginx-unprivileged-fix-version = "docker-registry-mirror.netcetera.com/nginxinc/nginx-unprivileged:1.18-alpine"
nginx = "docker-registry-mirror.netcetera.com/nginx:latest"
polinux-stress = "docker-registry-mirror.netcetera.com/polinux/stress:latest"
busybox = "docker-registry-mirror.netcetera.com/busybox:1.28"
