[params]
enabledModule = "base rancher customer netcetera"

registryMirror = "docker-registry-mirror.netcetera.com/"
baseRegistryUrl = "docker-registry-mirror.netcetera.com/acend" # for acend images

customer = "netcetera"
