# Secrets are stored in the same file as the Deployment for demo purposes. Don't do this for production workloads!
---
apiVersion: v1
data:
  password: bXlzcWxwYXNzd29yZA==
kind: Secret
metadata:
  name: mysql-password
---
apiVersion: v1
data:
  password: bXlzcWxyb290cGFzc3dvcmQ=
kind: Secret
metadata:
  name: mysql-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: docker-registry.mobicorp.ch/puzzle/k8s/kurs/mysql:5.6
          name: mysql
          args:
            - "--ignore-db-dir=lost+found"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-password
                  key: password
            - name: MYSQL_DATABASE
              value: example
            - name: MYSQL_USER
              value: example
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-password
                  key: password
          livenessProbe:
            tcpSocket:
              port: 3306
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
