title = "OpenShift Basics Training"
languageCode = "en-us"

[Languages]
[Languages.en]
title = "Openshift Basics Training"

[params]
enabledModule = "base openshift"
distroName = "OpenShift"
cliToolName = "oc"

[params.pdf]
title="OpenShift Basics Training"
