title = "OpenShift Basics Training"
languageCode = "en-us"

[Languages]
[Languages.en]
title = "OpenShift Basics Training"

[params]
enabledModule = "base openshift"
distroName = "OpenShift"
cliToolName = "oc"
