theme = ["docsy-puzzle", "docsy-plus", "docsy"]

[params]
enabledModule = "base techlab"
copyright = "APPUiO"
imagePrefix = "appuio_"

[[Languages.en.menu.main]]
copyright = "APPUiO"
url = "https://appuio.ch"

############################## social links ##############################
[params.links]
[[params.links.developer]]
name = "GitHub"
icon = "fab fa-github"
url = "https://github.com/acend/kubernetes-basics-training"

[[params.links.user]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/appuio"

[[params.links.user]]
name = "LinkedIn"
icon = "fab fa-linkedin-in"
url = "https://www.linkedin.com/company/appuio/"
