apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-public
  labels:
    app: kubernetes-techlab
  name: kubernetes-techlab
  namespace: dreng-kubernetestechlab-prod
spec:
  rules:
  - host: kubernetes-techlab.k8s.puzzle.ch
    http:
      paths:
      - backend:
          serviceName: kubernetes-techlab
          servicePort: 8080
  tls:
  - hosts:
    - kubernetes-techlab.k8s.puzzle.ch