---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-web-python
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
spec:
  rules:
    - host: example-web-python-<namespace>.training.test.netcetera.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: example-web-python
                port: 
                  number: 5000
