theme = ["docsy-puzzle", "docsy-plus", "docsy"]

[params]
enabledModule = "base rancher customer mobi"
copyright = "Puzzle ITC GmbH"
imagePrefix = "puzzle_"
customer = "mobi"

[params.images]
acendAwesomeApp-example-web-go = "REGISTRY-URL/puzzle/k8s/kurs/example-web-go:latest"
acendAwesomeApp-example-web-python = "REGISTRY-URL/puzzle/k8s/kurs/example-web-python:latest"
nginxinc-nginx-unprivileged = "REGISTRY-URL/puzzle/k8s/kurs/nginx-unprivileged:latest"
nginxinc-nginx-unprivileged-fix-version = "REGISTRY-URL/puzzle/k8s/kurs/nginx-unprivileged:1.18-alpine"
nginx = "REGISTRY-URL/puzzle/k8s/kurs/nginx:latest"
stress = "REGISTRY-URL/puzzle/k8s/kurs/stress:latest"
busybox = "REGISTRY-URL/puzzle/k8s/kurs/busybox:1.28"

[[Languages.en.menu.main]]
copyright = "Puzzle ITC GmbH"
url = "https://www.puzzle.ch"

[params.replaceContent]
allowedHrefHosts = ['localhost', 'puzzle.ch', 'acend.ch']

[[params.replaceContent.placeholders]]
placeholder = "REGISTRY-URL"
queryParam = "r"
defaultValue = "REGISTRY-URL"

[[params.replaceContent.placeholders]]
placeholder = "<proxy>:<port>"
queryParam = "p"
defaultValue = "<proxy>:<port>"

[[params.replaceContent.placeholders]]
placeholder = "<noproxy-list>"
queryParam = "n"
defaultValue = "<noproxy-list>"

[[params.replaceContent.placeholders]]
placeholder = "<appdomain>"
queryParam = "a"
defaultValue = "<appdomain>"

############################## social links ##############################
[params.links]
[[params.links.developer]]
name = "GitHub"
icon = "fab fa-github"
url = "https://github.com/acend/kubernetes-basics-training"

[[params.links.user]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/puzzleitc"

[[params.links.user]]
name = "LinkedIn"
icon = "fab fa-linkedin-in"
url = "https://linkedin.com/company/puzzle-itc/"
