name: Build Training

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - 
        name: Lint Markdown
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: "content *.md"
          config_file: ".markdownlint.json"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Build Latest Version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: |
            acend/kubernetes-basics-training:latest
            quay.io/acend/kubernetes-basics-training:latest
      - 
        name: Build Mobi Version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            HUGO_ENV=mobi
          push: false
          tags: |
            acend/kubernetes-basics-training:mobi
            quay.io/acend/kubernetes-basics-training:mobi
      - 
        name: Build Rancher Version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            HUGO_ENV=rancher
          push: false
          tags: |
            acend/kubernetes-basics-training:rancher
            quay.io/acend/kubernetes-basics-training:rancher
      - 
        name: Build OpenShift Version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            HUGO_ENV=openshift
          push: false
          tags: |
            acend/kubernetes-basics-training:openshift
            quay.io/acend/kubernetes-basics-training:openshift
