name: Housekeeping

on:
  workflow_dispatch

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - 
        name: 'Install Helm'
        uses: azure/setup-helm@v1
        with:
          version: v3.6.2
      - 
        name: Install Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: v1.21.2
      - 
        name: Create KUBECONFIG
        env:
          KUBE_CONFIG: '${{ secrets.KUBECONFIG_TEST }}'
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG" > $HOME/.kube/config
      - 
        name: List Open PRs
        uses: chrisaddy/list-open-prs@0.1.0
      - 
        name: Get all deployed PRs
        env:
          TRAINING_HELM_RELEASE: 'pr-${{ github.event.pull_request.number }}'
          TRAINING_NAMESPACE: 'acend-kubernetes-basics-training-test'
          TRAINING_VERSION: '${{ github.sha }}'
        run: |
          helm --kubeconfig $HOME/.kube/config --namespace=$TRAINING_NAMESPACE ls -o json | jq '.[] | .name'

