name: master-publish

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to Quay.io Container Registry
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}
      - 
        name: Build and Push Latest Version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            acend/kubernetes-basics-training:latest
            quay.io/acend/kubernetes-basics-training:latest
      - 
        name: Build and Push Mobi Version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            ACEND_HUGO_ENV=mobi
          push: true
          tags: |
            acend/kubernetes-basics-training:mobi
            quay.io/acend/kubernetes-basics-training:mobi
      - 
        name: Build and Push Rancher Version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            ACEND_HUGO_ENV=rancher
          push: true
          tags: |
            acend/kubernetes-basics-training:rancher
            quay.io/acend/kubernetes-basics-training:rancher
      - 
        name: Build and Push OpenShift Version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            ACEND_HUGO_ENV=openshift
          push: true
          tags: |
            acend/kubernetes-basics-training:openshift
            quay.io/acend/kubernetes-basics-training:openshift